version: '3.8'
services:
  postgres:
    image: postgres:12.16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile  # 이 부분을 명시적으로 설정하지 않으면 기본적으로 `Dockerfile`을 사용함
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
