spring:
  datasource:
    # docker compose 사용 시 수정 예정
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
