spring:
  datasource:
    # docker compose 사용 시 수정 예정
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

keycloak:
  enabled: true
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_HOST_URL}
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT_ID}
  use-resource-role-mappings: true
  bearer-only: true

custom-keycloak:
  client_secret: ${KEYCLOAK_CLIENT_SECRET}
  grant_type: ${KEYCLOAK_GRANT_TYPE}
  admin_username: ${KEYCLOAK_ADMIN_USERNAME}
  admin_password: ${KEYCLOAK_ADMIN_PASSWORD}
  get_token_url: ${KEYCLOAK_GET_TOKEN_URL}
  validate_token_url: ${KEYCLOAK_VALIDATE_TOKEN_URL}
  signup_url: ${KEYCLOAK_SIGNUP_URL}

